### PR TITLE
Improved the inference code to make it easier to get started with using inference for this project.

### PR DESCRIPTION
**Pull request by owlwang**
In order not to disrupt the original structure, a separate inference folder was added.

```
usage: python3 inference.py [-h] --audio_path AUDIO_PATH [--output_dir OUTPUT_DIR]

TVSM Inference

optional arguments:
  -h, --help            show this help message and exit
  --audio_path AUDIO_PATH
  --output_dir OUTPUT_DIR
```

The following are the optimized contents:
- Stopped using LFS and added the original Lightning checkpoint model files.
- Supports scanning a single file or a directory.
- Streamlined and optimized the original inference code, keeping only useful parameters and code. 
- Reduced dependencies needed for inference.
- Converted the lightning model into a torch model (while reducing size).
- Optimized the output results for ease of users setting their own thresholds.

### CODE REVIEW

**Comment by ruohoruotsi** [comment]
@biboamy @owlwang was there a problem with this PR such that it was closed rather than merged? Asking as some of the updates for inferencing look rather useful

**Comment by owlwang** [comment]
Hi, @ruohoruotsi , it seems that this project lacks maintenance and the authors are not very active on GitHub. Therefore, I have decided to close this PR. If you need it, you can use this code directly.

**Comment by biboamy** [comment]
@owlwang thanks for the amazing contribution! And @ruohoruotsi thanks for bringing this up. Sorry for the delay; I was swept away by some life-changing events over the past few months and didn't notice this merge request. I will reopen it now. It looks good to me! I will just add a few checking functions (mono checking and sample rate checking) and update the README to include this inference code. After that, it will be ready to merge. I will try to finish this by the end of today. 

Thanks again for the contribution!

**Comment by ruohoruotsi** [comment]
Thank you @biboamy ! No problem, I hope the life-changing events are settling 🙏 . The reason I brought up this inference code was that I had in parallel started to do some of the reorganization (for inference) that @owlwang already did!! So I thank him for this work! This effort brings this project closer to the ease-of-use of https://github.com/snakers4/silero-vad

Ultimately, for my own OSS needs/projects, I would like to make this into a PyPI project, so that we can say `pip install sm-detect" (example) and have it installed directly. What do you think?

The other improvement I'd like to submit an issue/PR for is to post-process the activations into a list of tuples `(start_frame, stop_frame, 'm|s')` that can be returned inline in code (versus writing to json/csv) What do you think? Is this interesting?

**Comment by biboamy** [comment]
@ruohoruotsi Agree, having a pip install version is definitely more convenient. I think returning tuples inline in code is also helpful. Another thing I want to do for post-process (but did't have time) is to merge all the small frames into a chunk if they are continuous. 

Anyway, please feel free to open any feature request/issue/PR. I have more time now so I will review it faster and can work on some issues! 😃

**Comment by owlwang** [comment]
Hi @biboamy , thank you for the merge and your work, hope everything is going well.

I actually recently completed the step of merging the small frames into chunks, and will submit the updated code once I've finished cleaning it up.

**Comment by biboamy** [comment]
@owlwang That would be awesome. Thank you so much!

**Pull request merged**
